# Default colors
[colors.primary]
background = '#121212'
foreground = '#eeeeee'

# Normal colors
[colors.normal]
black   = '#282828'
red     = '#e23838'
green   = '#5ebd3e'
yellow  = '#ffb900'
cyan    = '#f78200'
magenta = '#973999'
blue    = '#009cdf'
white   = '#eeeeee'

# Bright colors
[colors.bright]
black   = '#282828'
red     = '#e23838'
green   = '#5ebd3e'
yellow  = '#ffb900'
cyan    = '#f78200'
magenta = '#973999'
blue    = '#009cdf'
white   = '#eeeeee'


#
# black   = '#4c4c4c'
# red     = '#f43753'
# green   = '#c9d05c'
# yellow  = '#ffc24b'
# blue    = '#73cef5'
# cyan    = '#F9A84D'
# magenta = '#AC61AD'
# white   = '#feffff'
